/** Ankara düğün / video aramaları — metadata ve landing sayfalarında ortak */
export const ANKARA_SEO_KEYWORDS = [
  // Ticari / yüksek niyet
  "ankara düğün fotoğrafçısı",
  "ankara düğün fotoğrafçısı fiyatları",
  "ankara düğün fotoğrafçısı fiyatları 2026",
  "düğün fotoğrafçısı fiyatları",
  "düğün paketleri fiyatları",
  "en iyi düğün fotoğrafçısı ankara",
  "ankara düğün videosu",
  "ankara düğün klibi",
  "ankara gelin alma çekimi",
  "ankara gelin alma klibi",
  "gelin alma klip ankara",
  "ankara dış çekim",
  "ankara dış çekim fiyatları",
  "ankara dış çekim mekanları",
  "ankara dış çekim platoları",
  "ankara plato çekimi",
  "ankara kına çekimi",
  "ankara nişan fotoğrafçısı",
  "ankara salon düğün çekimi",
  "ankara sinematik düğün videosu",
  "ankara drone düğün çekimi",
  "save the date çekimi ankara",
  "ankara wedding photographer",
  "ankara wedding videographer",
  "düğün fotoğrafçısı ankara",
  "düğün videosu ankara",
  // Bilgi amaçlı / long-tail (PAA)
  "düğün fotoğrafçısı ne kadar",
  "dış çekim ne kadar sürer",
  "düğün fotoğrafçısı kaç ay önceden ayarlanmalı",
  "plato çekimi nedir",
  "düğün albümü fiyatları",
  // Marka
  "red media ankara",
  "redmedya",
  "redmedya.co",
] as const;

export const ANKARA_DISTRICTS = [
  "Çankaya",
  "Keçiören",
  "Yenimahalle",
  "Mamak",
  "Etimesgut",
  "Sincan",
  "Pursaklar",
  "Altındağ",
  "Gölbaşı",
  "Polatlı",
] as const;
